export const dynamic = 'force-dynamic';

import { NextRequest } from 'next/server';
import { Resend } from 'resend';
import type { ForgeBriefData, CoreFeature, Milestone } from '@/app/lib/forge/types';

function priorityColor(p: string): string {
  if (p === 'P1') return '#00f0ff';
  if (p === 'P2') return '#8b5cf6';
  return '#6b7280';
}

function buildHtml(brief: ForgeBriefData): string {
  const { client, project, milestones, total_estimated_timeline, next_step } = brief;

  const featuresRows = project.core_features
    .map(
      (f: CoreFeature) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #1f1f2e;color:#e8e9ed;font-size:14px;">${f.feature}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #1f1f2e;text-align:center;">
          <span style="display:inline-block;padding:2px 10px;border-radius:9999px;font-size:12px;font-weight:700;font-family:monospace;background:${priorityColor(f.priority)}20;color:${priorityColor(f.priority)};border:1px solid ${priorityColor(f.priority)}40;">${f.priority}</span>
        </td>
      </tr>`
    )
    .join('');

  const milestonesHtml = milestones
    .map(
      (m: Milestone, i: number) => `
      <div style="margin-bottom:16px;padding:16px;background:#0f0f1a;border-radius:10px;border-left:3px solid #00f0ff;">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;">
          <strong style="color:#f8f9fa;font-size:15px;">Milestone ${i + 1}: ${m.title}</strong>
          <span style="color:#00f0ff;font-family:monospace;font-size:12px;">${m.estimated_duration}</span>
        </div>
        <ul style="margin:0;padding-left:18px;color:#a0a0ab;font-size:13px;line-height:1.7;">
          ${m.deliverables.map((d: string) => `<li>${d}</li>`).join('')}
        </ul>
      </div>`
    )
    .join('');

  const outOfScopeHtml = project.out_of_scope
    .map((item: string) => `<li style="margin-bottom:6px;">${item}</li>`)
    .join('');

  const openQuestionsHtml = project.open_questions
    .map((q: string) => `<li style="margin-bottom:6px;">${q}</li>`)
    .join('');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#0a0a0f;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:680px;margin:0 auto;padding:40px 24px;">

    <!-- Header -->
    <div style="margin-bottom:32px;padding-bottom:24px;border-bottom:1px solid #1f1f2e;">
      <div style="display:inline-block;padding:4px 12px;background:rgba(0,240,255,0.1);border:1px solid rgba(0,240,255,0.2);border-radius:9999px;margin-bottom:16px;">
        <span style="color:#00f0ff;font-size:11px;font-family:monospace;letter-spacing:0.1em;font-weight:700;">GENERATED BY FORGE</span>
      </div>
      <h1 style="margin:0 0 8px;color:#f8f9fa;font-size:28px;font-weight:700;">${project.name}</h1>
      <p style="margin:0;color:#a0a0ab;font-size:14px;">Project brief for <strong style="color:#e8e9ed;">${client.name}</strong></p>
    </div>

    <!-- Client Info -->
    <div style="margin-bottom:28px;padding:16px;background:#0f0f1a;border-radius:12px;border:1px solid #1f1f2e;">
      <p style="margin:0 0 6px;color:#a0a0ab;font-size:12px;font-family:monospace;letter-spacing:0.1em;text-transform:uppercase;">Client</p>
      <p style="margin:0 0 4px;color:#f8f9fa;font-size:16px;font-weight:600;">${client.name}</p>
      <a href="mailto:${client.email}" style="color:#00f0ff;font-size:14px;text-decoration:none;">${client.email}</a>
    </div>

    <!-- Project Summary -->
    <div style="margin-bottom:28px;">
      <h2 style="margin:0 0 12px;color:#f8f9fa;font-size:16px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;">Project Summary</h2>
      <p style="margin:0 0 12px;color:#e8e9ed;font-size:14px;line-height:1.7;">${project.summary}</p>
      <p style="margin:0;color:#a0a0ab;font-size:14px;"><strong style="color:#8b5cf6;">Target Users:</strong> ${project.target_users}</p>
    </div>

    <!-- Core Features -->
    <div style="margin-bottom:28px;">
      <h2 style="margin:0 0 12px;color:#f8f9fa;font-size:16px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;">Core Features</h2>
      <table style="width:100%;border-collapse:collapse;background:#0f0f1a;border-radius:10px;overflow:hidden;border:1px solid #1f1f2e;">
        <thead>
          <tr style="background:#1a1a2e;">
            <th style="padding:10px 12px;text-align:left;color:#a0a0ab;font-size:12px;font-family:monospace;letter-spacing:0.08em;font-weight:600;">FEATURE</th>
            <th style="padding:10px 12px;text-align:center;color:#a0a0ab;font-size:12px;font-family:monospace;letter-spacing:0.08em;font-weight:600;">PRIORITY</th>
          </tr>
        </thead>
        <tbody>${featuresRows}</tbody>
      </table>
    </div>

    <!-- Tech Stack -->
    <div style="margin-bottom:28px;padding:16px;background:#0f0f1a;border-radius:12px;border:1px solid #1f1f2e;">
      <h2 style="margin:0 0 10px;color:#f8f9fa;font-size:16px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;">Recommended Tech Stack</h2>
      <p style="margin:0;color:#e8e9ed;font-size:14px;line-height:1.7;font-family:monospace;">${project.tech_stack_recommendation}</p>
    </div>

    <!-- Milestones -->
    <div style="margin-bottom:28px;">
      <h2 style="margin:0 0 16px;color:#f8f9fa;font-size:16px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;">Milestones</h2>
      ${milestonesHtml}
    </div>

    <!-- Timeline -->
    <div style="margin-bottom:28px;padding:16px;background:rgba(0,240,255,0.05);border-radius:12px;border:1px solid rgba(0,240,255,0.15);">
      <p style="margin:0 0 4px;color:#a0a0ab;font-size:12px;font-family:monospace;text-transform:uppercase;letter-spacing:0.1em;">Total Estimated Timeline</p>
      <p style="margin:0;color:#00f0ff;font-size:20px;font-weight:700;font-family:monospace;">${total_estimated_timeline}</p>
    </div>

    <!-- Out of Scope -->
    ${project.out_of_scope.length > 0 ? `
    <div style="margin-bottom:28px;">
      <h2 style="margin:0 0 12px;color:#f8f9fa;font-size:16px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;">Out of Scope</h2>
      <ul style="margin:0;padding-left:18px;color:#a0a0ab;font-size:14px;line-height:1.7;">${outOfScopeHtml}</ul>
    </div>` : ''}

    <!-- Open Questions -->
    ${project.open_questions.length > 0 ? `
    <div style="margin-bottom:28px;">
      <h2 style="margin:0 0 12px;color:#f8f9fa;font-size:16px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;">Open Questions</h2>
      <ul style="margin:0;padding-left:18px;color:#a0a0ab;font-size:14px;line-height:1.7;">${openQuestionsHtml}</ul>
    </div>` : ''}

    <!-- CTA -->
    <div style="margin-top:36px;padding-top:24px;border-top:1px solid #1f1f2e;text-align:center;">
      <p style="margin:0 0 16px;color:#a0a0ab;font-size:13px;">${next_step}</p>
      <a href="https://masabfarooque.com/contact" style="display:inline-block;padding:12px 28px;background:linear-gradient(135deg,rgb(0,240,255),rgb(139,92,246));color:#0a0a0f;font-size:14px;font-weight:700;text-decoration:none;border-radius:10px;">Contact Masab</a>
    </div>

    <p style="margin:32px 0 0;text-align:center;color:#3a3a4a;font-size:11px;font-family:monospace;">Generated by Forge · masabfarooque.com</p>
  </div>
</body>
</html>`;
}

export async function POST(request: NextRequest) {
  if (!process.env.RESEND_API_KEY) {
    return new Response(
      JSON.stringify({ error: 'Resend API key not configured.' }),
      { status: 503, headers: { 'Content-Type': 'application/json' } }
    );
  }

  let body: { brief: ForgeBriefData };
  try {
    body = await request.json();
  } catch {
    return new Response(
      JSON.stringify({ error: 'Invalid request body.' }),
      { status: 400, headers: { 'Content-Type': 'application/json' } }
    );
  }

  const { brief } = body;
  const resend = new Resend(process.env.RESEND_API_KEY);

  const subject = `[Forge] New Brief — ${brief.project.name} — ${brief.client.name}`;
  const html = buildHtml(brief);

  try {
    await resend.emails.send({
      from: 'Forge <forge@masabfarooque.com>',
      to: 'masabfarooque1122@gmail.com',
      subject,
      html,
    });
    return new Response(JSON.stringify({ success: true }), {
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return new Response(
      JSON.stringify({ error: 'Failed to send email.', details: message }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }
}
