'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import type { ForgeBriefData, CoreFeature, Milestone } from '@/app/lib/forge/types';

interface ForgeBriefProps {
  brief: ForgeBriefData;
}

function PriorityBadge({ priority }: { priority: 'P1' | 'P2' | 'P3' }) {
  const colors: Record<string, { bg: string; border: string; text: string }> = {
    P1: { bg: 'var(--accent-cyan-subtle)', border: 'var(--accent-cyan-border)', text: 'var(--accent-cyan)' },
    P2: { bg: 'var(--accent-violet-subtle)', border: 'var(--accent-violet-border)', text: 'var(--accent-violet)' },
    P3: { bg: 'rgba(107,114,128,0.15)', border: 'rgba(107,114,128,0.3)', text: 'rgb(156,163,175)' },
  };
  const c = colors[priority];
  return (
    <span
      style={{
        display: 'inline-block',
        padding: '2px 10px',
        borderRadius: '9999px',
        fontSize: 11,
        fontWeight: 700,
        fontFamily: 'var(--font-jetbrains), monospace',
        letterSpacing: '0.06em',
        background: c.bg,
        border: `1px solid ${c.border}`,
        color: c.text,
      }}
    >
      {priority}
    </span>
  );
}

export default function ForgeBrief({ brief }: ForgeBriefProps) {
  const { project, milestones, total_estimated_timeline, next_step, client } = brief;

  const generatePDF = async () => {
    const { default: jsPDF } = await import('jspdf');
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    const pageW = doc.internal.pageSize.getWidth();
    const margin = 18;
    const contentW = pageW - margin * 2;
    let y = margin;

    const addText = (
      text: string,
      x: number,
      yPos: number,
      opts: { fontSize?: number; bold?: boolean; color?: [number, number, number]; maxWidth?: number } = {}
    ) => {
      const { fontSize = 10, bold = false, color = [248, 249, 250], maxWidth } = opts;
      doc.setFontSize(fontSize);
      doc.setFont('helvetica', bold ? 'bold' : 'normal');
      doc.setTextColor(color[0], color[1], color[2]);
      if (maxWidth) {
        const lines = doc.splitTextToSize(text, maxWidth);
        doc.text(lines, x, yPos);
        return lines.length * (fontSize * 0.4);
      }
      doc.text(text, x, yPos);
      return fontSize * 0.4;
    };

    const checkPage = (needed: number) => {
      if (y + needed > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = margin;
      }
    };

    // Header background
    doc.setFillColor(10, 10, 15);
    doc.rect(0, 0, pageW, doc.internal.pageSize.getHeight(), 'F');

    // Title
    y += 2;
    addText('PROJECT BRIEF', margin, y, { fontSize: 9, bold: true, color: [0, 200, 215] });
    y += 7;
    addText(project.name, margin, y, { fontSize: 20, bold: true, color: [248, 249, 250] });
    y += 8;
    addText(`Client: ${client.name} · ${client.email}`, margin, y, { fontSize: 9, color: [160, 160, 171] });
    y += 4;
    addText('Generated by Forge · masabfarooque.com', margin, y, { fontSize: 8, color: [80, 80, 90] });
    y += 10;

    // Divider
    doc.setDrawColor(40, 40, 60);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageW - margin, y);
    y += 10;

    // Summary
    addText('PROJECT SUMMARY', margin, y, { fontSize: 9, bold: true, color: [0, 200, 215] });
    y += 6;
    const summaryLines = doc.splitTextToSize(project.summary, contentW);
    addText(project.summary, margin, y, { fontSize: 10, color: [220, 220, 235], maxWidth: contentW });
    y += summaryLines.length * 5 + 4;
    addText(`Target Users: ${project.target_users}`, margin, y, { fontSize: 10, color: [160, 160, 171], maxWidth: contentW });
    y += 10;

    // Core Features
    checkPage(30);
    addText('CORE FEATURES', margin, y, { fontSize: 9, bold: true, color: [139, 92, 246] });
    y += 7;
    project.core_features.forEach((f: CoreFeature) => {
      checkPage(8);
      const pColor: [number, number, number] =
        f.priority === 'P1' ? [0, 200, 215] : f.priority === 'P2' ? [139, 92, 246] : [120, 120, 130];
      addText(`[${f.priority}]`, margin, y, { fontSize: 9, bold: true, color: pColor });
      addText(f.feature, margin + 12, y, { fontSize: 10, color: [220, 220, 235], maxWidth: contentW - 14 });
      y += 6;
    });
    y += 4;

    // Tech Stack
    checkPage(20);
    addText('TECH STACK RECOMMENDATION', margin, y, { fontSize: 9, bold: true, color: [0, 200, 215] });
    y += 6;
    const techLines = doc.splitTextToSize(project.tech_stack_recommendation, contentW);
    addText(project.tech_stack_recommendation, margin, y, { fontSize: 10, color: [220, 220, 235], maxWidth: contentW });
    y += techLines.length * 5 + 8;

    // Milestones
    checkPage(20);
    addText('MILESTONES', margin, y, { fontSize: 9, bold: true, color: [139, 92, 246] });
    y += 7;
    milestones.forEach((m: Milestone, i: number) => {
      checkPage(20);
      addText(`${i + 1}. ${m.title}`, margin, y, { fontSize: 11, bold: true, color: [248, 249, 250] });
      addText(m.estimated_duration, pageW - margin - 30, y, { fontSize: 9, color: [0, 200, 215] });
      y += 6;
      m.deliverables.forEach((d: string) => {
        checkPage(6);
        addText(`• ${d}`, margin + 4, y, { fontSize: 9, color: [160, 160, 171], maxWidth: contentW - 8 });
        y += 5;
      });
      y += 4;
    });

    // Timeline
    checkPage(16);
    doc.setDrawColor(0, 200, 215);
    doc.setLineWidth(0.2);
    doc.line(margin, y, pageW - margin, y);
    y += 8;
    addText('TOTAL ESTIMATED TIMELINE', margin, y, { fontSize: 9, bold: true, color: [0, 200, 215] });
    y += 6;
    addText(total_estimated_timeline, margin, y, { fontSize: 14, bold: true, color: [0, 200, 215] });
    y += 10;

    // Out of scope
    if (project.out_of_scope.length > 0) {
      checkPage(16);
      addText('OUT OF SCOPE', margin, y, { fontSize: 9, bold: true, color: [180, 80, 80] });
      y += 6;
      project.out_of_scope.forEach((item: string) => {
        checkPage(6);
        addText(`• ${item}`, margin + 4, y, { fontSize: 9, color: [160, 160, 171], maxWidth: contentW - 8 });
        y += 5;
      });
      y += 4;
    }

    // Next step
    checkPage(12);
    addText('NEXT STEP', margin, y, { fontSize: 9, bold: true, color: [0, 200, 215] });
    y += 6;
    addText(next_step, margin, y, { fontSize: 10, color: [220, 220, 235], maxWidth: contentW });

    doc.save(`${project.name.replace(/\s+/g, '-').toLowerCase()}-brief.pdf`);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
      style={{
        background: 'var(--bg-primary)',
        border: '1px solid var(--accent-cyan-border)',
        borderRadius: 16,
        overflow: 'hidden',
        marginTop: 24,
      }}
    >
      {/* Header */}
      <div
        style={{
          padding: '20px 24px',
          background: 'linear-gradient(135deg, rgba(0,240,255,0.06), rgba(139,92,246,0.06))',
          borderBottom: '1px solid var(--border-base)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexWrap: 'wrap',
          gap: 12,
        }}
      >
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
            <span
              style={{
                padding: '3px 10px',
                background: 'var(--accent-cyan-subtle)',
                border: '1px solid var(--accent-cyan-border)',
                borderRadius: 9999,
                fontSize: 10,
                fontFamily: 'var(--font-jetbrains), monospace',
                letterSpacing: '0.1em',
                color: 'var(--accent-cyan)',
                fontWeight: 700,
              }}
            >
              GENERATED BY FORGE
            </span>
          </div>
          <h2 style={{ margin: 0, fontSize: 22, fontWeight: 700, color: 'var(--text-1)' }}>{project.name}</h2>
          <p style={{ margin: '4px 0 0', fontSize: 13, color: 'var(--text-3)' }}>
            Brief for <span style={{ color: 'var(--text-2)', fontWeight: 600 }}>{client.name}</span>
          </p>
        </div>
        <div style={{ display: 'flex', gap: 10 }}>
          <button
            onClick={generatePDF}
            style={{
              padding: '9px 18px',
              background: 'var(--accent-cyan-subtle)',
              border: '1px solid var(--accent-cyan-border)',
              borderRadius: 10,
              color: 'var(--accent-cyan)',
              fontSize: 13,
              fontWeight: 600,
              cursor: 'pointer',
              fontFamily: 'var(--font-jetbrains), monospace',
              transition: 'all 0.2s ease',
            }}
            onMouseEnter={e => {
              (e.currentTarget as HTMLButtonElement).style.background = 'var(--accent-cyan-border)';
            }}
            onMouseLeave={e => {
              (e.currentTarget as HTMLButtonElement).style.background = 'var(--accent-cyan-subtle)';
            }}
          >
            Export PDF
          </button>
          <Link
            href="/contact"
            style={{
              padding: '9px 18px',
              background: 'linear-gradient(135deg, rgb(0,240,255), rgb(139,92,246))',
              border: 'none',
              borderRadius: 10,
              color: '#0a0a0f',
              fontSize: 13,
              fontWeight: 700,
              cursor: 'pointer',
              textDecoration: 'none',
              display: 'inline-block',
            }}
          >
            Contact Masab
          </Link>
        </div>
      </div>

      <div style={{ padding: '24px' }}>
        {/* Summary */}
        <Section title="Project Summary" accentColor="var(--accent-cyan)">
          <p style={{ margin: '0 0 10px', fontSize: 14, color: 'var(--text-2)', lineHeight: 1.7 }}>{project.summary}</p>
          <p style={{ margin: 0, fontSize: 13, color: 'var(--text-3)' }}>
            <span style={{ color: 'var(--accent-violet)', fontWeight: 600 }}>Target Users: </span>
            {project.target_users}
          </p>
        </Section>

        {/* Core Features */}
        <Section title="Core Features" accentColor="var(--accent-violet)">
          <div
            style={{
              border: '1px solid var(--border-base)',
              borderRadius: 10,
              overflow: 'hidden',
            }}
          >
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ background: 'var(--bg-card)' }}>
                  <th
                    style={{
                      padding: '8px 12px',
                      textAlign: 'left',
                      fontSize: 11,
                      fontFamily: 'var(--font-jetbrains), monospace',
                      letterSpacing: '0.08em',
                      color: 'var(--text-3)',
                      fontWeight: 600,
                    }}
                  >
                    FEATURE
                  </th>
                  <th
                    style={{
                      padding: '8px 12px',
                      textAlign: 'center',
                      fontSize: 11,
                      fontFamily: 'var(--font-jetbrains), monospace',
                      letterSpacing: '0.08em',
                      color: 'var(--text-3)',
                      fontWeight: 600,
                      width: 80,
                    }}
                  >
                    PRIORITY
                  </th>
                </tr>
              </thead>
              <tbody>
                {project.core_features.map((f: CoreFeature, i: number) => (
                  <tr key={i} style={{ borderTop: '1px solid var(--border-base)' }}>
                    <td style={{ padding: '9px 12px', fontSize: 13, color: 'var(--text-2)' }}>{f.feature}</td>
                    <td style={{ padding: '9px 12px', textAlign: 'center' }}>
                      <PriorityBadge priority={f.priority} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Section>

        {/* Tech Stack */}
        <Section title="Recommended Tech Stack" accentColor="var(--accent-cyan)">
          <p
            style={{
              margin: 0,
              fontSize: 13,
              color: 'var(--text-2)',
              lineHeight: 1.7,
              fontFamily: 'var(--font-jetbrains), monospace',
              background: 'var(--bg-card)',
              padding: '12px 16px',
              borderRadius: 8,
              border: '1px solid var(--border-base)',
            }}
          >
            {project.tech_stack_recommendation}
          </p>
        </Section>

        {/* Milestones */}
        <Section title="Milestones" accentColor="var(--accent-violet)">
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {milestones.map((m: Milestone, i: number) => (
              <div
                key={i}
                style={{
                  background: 'var(--bg-card)',
                  border: '1px solid var(--border-base)',
                  borderLeft: '3px solid var(--accent-cyan)',
                  borderRadius: 10,
                  padding: '14px 16px',
                }}
              >
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    marginBottom: 10,
                  }}
                >
                  <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-1)' }}>
                    <span style={{ color: 'var(--accent-cyan)', opacity: 0.5, fontFamily: 'monospace', marginRight: 8 }}>
                      {String(i + 1).padStart(2, '0')}
                    </span>
                    {m.title}
                  </span>
                  <span
                    style={{
                      fontSize: 11,
                      fontFamily: 'var(--font-jetbrains), monospace',
                      color: 'var(--accent-cyan)',
                      background: 'var(--accent-cyan-subtle)',
                      border: '1px solid var(--accent-cyan-border)',
                      padding: '2px 10px',
                      borderRadius: 9999,
                    }}
                  >
                    {m.estimated_duration}
                  </span>
                </div>
                <ul style={{ margin: 0, padding: '0 0 0 16px' }}>
                  {m.deliverables.map((d: string, j: number) => (
                    <li key={j} style={{ fontSize: 13, color: 'var(--text-3)', marginBottom: 4, lineHeight: 1.5 }}>
                      {d}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </Section>

        {/* Timeline */}
        <div
          style={{
            padding: '16px 20px',
            background: 'var(--accent-cyan-subtle)',
            border: '1px solid var(--accent-cyan-border)',
            borderRadius: 12,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            flexWrap: 'wrap',
            gap: 10,
            marginBottom: 20,
          }}
        >
          <span style={{ fontSize: 12, fontFamily: 'var(--font-jetbrains), monospace', color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
            Total Estimated Timeline
          </span>
          <span style={{ fontSize: 20, fontWeight: 700, color: 'var(--accent-cyan)', fontFamily: 'var(--font-jetbrains), monospace' }}>
            {total_estimated_timeline}
          </span>
        </div>

        {/* Out of Scope */}
        {project.out_of_scope.length > 0 && (
          <Section title="Out of Scope" accentColor="rgba(244,63,94,0.8)">
            <ul style={{ margin: 0, padding: '0 0 0 16px' }}>
              {project.out_of_scope.map((item: string, i: number) => (
                <li key={i} style={{ fontSize: 13, color: 'var(--text-3)', marginBottom: 6, lineHeight: 1.6 }}>
                  {item}
                </li>
              ))}
            </ul>
          </Section>
        )}

        {/* Open Questions */}
        {project.open_questions.length > 0 && (
          <Section title="Open Questions" accentColor="rgba(251,191,36,0.8)">
            <ul style={{ margin: 0, padding: '0 0 0 16px' }}>
              {project.open_questions.map((q: string, i: number) => (
                <li key={i} style={{ fontSize: 13, color: 'var(--text-3)', marginBottom: 6, lineHeight: 1.6 }}>
                  {q}
                </li>
              ))}
            </ul>
          </Section>
        )}

        {/* Next Step */}
        <div
          style={{
            marginTop: 8,
            padding: '20px 24px',
            background: 'linear-gradient(135deg, rgba(0,240,255,0.06), rgba(139,92,246,0.06))',
            border: '1px solid var(--border-base)',
            borderRadius: 12,
            textAlign: 'center',
          }}
        >
          <p style={{ margin: '0 0 14px', fontSize: 13, color: 'var(--text-3)' }}>{next_step}</p>
          <Link
            href="/contact"
            style={{
              display: 'inline-block',
              padding: '11px 28px',
              background: 'linear-gradient(135deg, rgb(0,240,255), rgb(139,92,246))',
              borderRadius: 10,
              color: '#0a0a0f',
              fontSize: 14,
              fontWeight: 700,
              textDecoration: 'none',
            }}
          >
            Book a Discovery Call
          </Link>
        </div>
      </div>
    </motion.div>
  );
}

function Section({
  title,
  accentColor,
  children,
}: {
  title: string;
  accentColor: string;
  children: React.ReactNode;
}) {
  return (
    <div style={{ marginBottom: 24 }}>
      <h3
        style={{
          margin: '0 0 12px',
          fontSize: 11,
          fontWeight: 700,
          fontFamily: 'var(--font-jetbrains), monospace',
          letterSpacing: '0.12em',
          textTransform: 'uppercase',
          color: accentColor,
        }}
      >
        {title}
      </h3>
      {children}
    </div>
  );
}
