/**
 * Generated by scripts/gen-reviews.mjs. Do not edit by hand.
 * Source export: fiverr_reviews_20260801.json
 * 25 buyers, most recent first, 2026-07-21 back to 2025-01-26.
 */

export interface Review {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  rating: number;
  comment: string;
  date: string;
  avatar: string | null;
  price: string;
  days: number | null;
  /** How many orders this buyer has reviewed in total. */
  orders: number;
  industry: string | null;
}

export const reviewSummary = {
  total: 148,
  average: 4.85,
  countries: 23,
  repeatShare: 31,
  newest: '2026-07-21',
  profileUrl: 'https://www.fiverr.com/p_scribbles',
} as const;

export const reviews: Review[] = [
  {
    "id": "6a5f796019caf17bfb955e7e",
    "name": "alexfidelman",
    "country": "United States",
    "countryCode": "US",
    "rating": 5,
    "comment": "I had an amazing experience with Masab. He's a very experienced and professional developer and depth of his knowledge and expertise is truly impressive. I really enjoyed working with him and will continue to do so in the next phase of my project. it's a real pleasure working with him because of his responsiveness and corporation.. Highly recommended!",
    "date": "2026-07-21T14:23:21",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/profile/photos/63140781/original/photo.jpg",
    "price": "$100-$200",
    "days": 4,
    "orders": 1,
    "industry": null
  },
  {
    "id": "6a5628f425897951757c2408",
    "name": "kate_chord",
    "country": "Netherlands",
    "countryCode": "NL",
    "rating": 5,
    "comment": "Masab was easy to work with from the very beginning. He is a great communicator as well as being quick and professional.",
    "date": "2026-07-14T12:40:56",
    "avatar": null,
    "price": "$200-$400",
    "days": 17,
    "orders": 1,
    "industry": null
  },
  {
    "id": "6a52bba36c166f6d30f434fd",
    "name": "revivegir1",
    "country": "United States",
    "countryCode": "US",
    "rating": 5,
    "comment": "Super Satisfied!!! This is the third project Masab has completed for me, and he continues to be an excellent partner. He handled the full deployment of our platform, converting our files, hosting everything correctly, and getting multiple tools live, with real precision. His attention to detail stood out: he kept filenames and links exact, made sure every piece connected the way it was supposed to, and didn't let small things slip. He also went above and beyond what I asked, when we needed a consistent header and footer across the entire site, he built it properly as shared components instead of quick patches. But what impressed me most was his cooperation: no matter how many rounds of refinements I sent, he stayed patient, responsive, and easy to communicate with, and turned changes around fast. He consistently exceeded my expectations and clearly cares about getting the final result right, not just done. Three projects in, I keep coming back for a reason. I highly recommended.",
    "date": "2026-07-11T22:17:10",
    "avatar": null,
    "price": "$50-$100",
    "days": 1,
    "orders": 5,
    "industry": null
  },
  {
    "id": "6a42e0724abee975411a7105",
    "name": "revivegir1",
    "country": "United States",
    "countryCode": "US",
    "rating": 5,
    "comment": "Working with Masab has been a great experience. From the very beginning, he has been patient, professional, responsive, and genuinely committed to helping bring my vision to life. This project has been much more complex than a typical website. As the project evolved, there were many revisions, new ideas, and changes in direction, and Masab handled them with a positive attitude and a willingness to find solutions. He consistently communicated well, offered thoughtful suggestions, and was always open to feedback. What I appreciate most is that he didn't just focus on completing assigned tasks, he took the time to think about the overall user experience and offered valuable recommendations that improved the project. His idea of creating a homepage and discussing an admin dashboard are great examples of him thinking beyond the original scope and looking toward the long-term success of the platform. We're still actively working together as the project continues to evolve, and I look forward to continuing that collaboration. I highly recommend Masab to anyone looking for a knowledgeable, dependable, and talented web developer who truly cares about the quality of his work. Thank you, Masab! I appreciate everything you've done, and I'm excited to keep building together. With gratitude, Tia",
    "date": "2026-06-29T21:36:40",
    "avatar": null,
    "price": "$200-$400",
    "days": 4,
    "orders": 5,
    "industry": null
  },
  {
    "id": "6a3eb7de9cf3405331405245",
    "name": "talhapythoneer",
    "country": "Pakistan",
    "countryCode": "PK",
    "rating": 5,
    "comment": "Second time working with Masab, and he continues to impress. Delivered a high-performance Next.js application with server-side rendering, seamless API integration, and a fully responsive frontend. His full-stack web development skill set from design to deployment makes him a rare find on Fiverr. Will keep coming back, even for outsourcing!",
    "date": "2026-06-26T17:57:35",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/34a97d27358631efc5e176833ecb2f79-1776512303854/16cd5ff1-313d-4725-92ef-125fb7bbd6f2.JPG",
    "price": "Up to $50",
    "days": 1,
    "orders": 2,
    "industry": null
  },
  {
    "id": "6a2a5c6d484d8846bce651d1",
    "name": "talhapythoneer",
    "country": "Pakistan",
    "countryCode": "PK",
    "rating": 5,
    "comment": "I hired Masab to scrape product data, expecting a basic script that would output a JSON file and call it done. What I got instead was a full production-grade FastAPI backend service with SQLite persistence, REST endpoints, and APScheduler-driven automatic re-scraping every 6 hours. the real surprise was the API layer on top: endpoints for searching, sorting, filtering, and exporting products, plus a /status route that tracks run history and the next scheduled scrape. There is even a background mode for triggering manual scrapes without blocking the request. Masab clearly thought about the practical side of running this long-term",
    "date": "2026-06-11T07:23:12",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/34a97d27358631efc5e176833ecb2f79-1776512303854/16cd5ff1-313d-4725-92ef-125fb7bbd6f2.JPG",
    "price": "Up to $50",
    "days": 1,
    "orders": 2,
    "industry": null
  },
  {
    "id": "6a0177fe8c37913214755c74",
    "name": "adouatt",
    "country": "France",
    "countryCode": "FR",
    "rating": 5,
    "comment": "I always love working with Masab and I am looking forward to more!",
    "date": "2026-05-11T07:01:11",
    "avatar": null,
    "price": "$600-$800",
    "days": 18,
    "orders": 2,
    "industry": null
  },
  {
    "id": "69e152514f6ef730448cd2f8",
    "name": "adouatt",
    "country": "France",
    "countryCode": "FR",
    "rating": 5,
    "comment": "Masab is someone who is easy to work with. He went over and beyond on each phases of this project. I am excited for rest!",
    "date": "2026-04-16T21:42:06",
    "avatar": null,
    "price": "$2,000-$3,000",
    "days": 49,
    "orders": 2,
    "industry": null
  },
  {
    "id": "69b59cfd71aad6423f8d6a1b",
    "name": "ksharma222",
    "country": "United States",
    "countryCode": "US",
    "rating": 5,
    "comment": "doesnt get better than this. he is the best in the business. his expertise are outstanding and response is even better. there is nothing masab cant figure out. having him by our side 2026 is going great for us.",
    "date": "2026-03-14T17:58:34",
    "avatar": null,
    "price": "Up to $50",
    "days": 1,
    "orders": 3,
    "industry": null
  },
  {
    "id": "69a074cb759dbd2e6bd5bf36",
    "name": "fibads",
    "country": "Netherlands",
    "countryCode": "NL",
    "rating": 5,
    "comment": "Absolutely amazing work. I've never had this experience with anyone before. Masab truly went above and beyond, unbelievable dedication and effort. He has a very strong understanding of complex scraping and everything that comes with it. The end product is amazing: a fully working SaaS platform that exceeded my expectations. I honestly can't thank him enough. We will definitely continue working together and keep building on this project in the future.",
    "date": "2026-02-26T16:54:44",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/ee2fce07156cf04166bb4c6da4b43df3-1741169853023/ed24eb71-42b8-4063-b1a8-e1c33b89bd33.jpg",
    "price": "$600-$800",
    "days": 28,
    "orders": 2,
    "industry": null
  },
  {
    "id": "6980b1366162b53dc9042818",
    "name": "fibads",
    "country": "Netherlands",
    "countryCode": "NL",
    "rating": 5,
    "comment": "Working with Masab was an absolute pleasure on our Autonomous Outreach Engine project. The result is completely bug-free, runs beautifully, and the dashboard is clean, intuitive, and perfectly executed! Masab shows outstanding code expertise and a deep understanding of complex concepts. He thinks proactively, communicates clearly with excellent language fluency, and is incredibly easy to collaborate with. The level of cooperation was top-tier from start to finish. I highly recommend Masab and will definitely be working with him again on future projects!",
    "date": "2026-02-02T14:38:27",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/ee2fce07156cf04166bb4c6da4b43df3-1741169853023/ed24eb71-42b8-4063-b1a8-e1c33b89bd33.jpg",
    "price": "$600-$800",
    "days": 16,
    "orders": 2,
    "industry": null
  },
  {
    "id": "6941f105e116ba37dd48ffb3",
    "name": "ksharma222",
    "country": "United States",
    "countryCode": "US",
    "rating": 5,
    "comment": "Thank you for your hard work on this project, your attention to detail, and your willingness to refine the work. I look forward to working with you on future projects.",
    "date": "2025-12-17T00:30:36",
    "avatar": null,
    "price": "$50-$100",
    "days": 6,
    "orders": 3,
    "industry": null
  },
  {
    "id": "693d1398e116ba37dd48ea2a",
    "name": "zahid119",
    "country": "Pakistan",
    "countryCode": "PK",
    "rating": 5,
    "comment": "good dev, helped me to fix a complex theme upgrade issues.",
    "date": "2025-12-13T08:07:53",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/5df5dd07453ef234e78a895364eb8b89-1656236629893/6aefe933-0a8f-4d38-b54e-9713116c5706.jpeg",
    "price": "Up to $50",
    "days": 3,
    "orders": 1,
    "industry": null
  },
  {
    "id": "693c250a5df9d100648a1df4",
    "name": "manelpassos",
    "country": "Portugal",
    "countryCode": "PT",
    "rating": 5,
    "comment": "Asked for a OCR development, and it was what I was expecting.",
    "date": "2025-12-12T14:22:02",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/db98401468ba19f383aec79357c1b63d-1764926975916/7e766688-6999-4e40-b66e-0d9d53031daf.jpg",
    "price": "$100-$200",
    "days": 10,
    "orders": 3,
    "industry": null
  },
  {
    "id": "6936aa36de734419431e1b70",
    "name": "polycarpbeta",
    "country": "Hong Kong",
    "countryCode": "HK",
    "rating": 5,
    "comment": "Delivered earlier than anticipated. Well done.",
    "date": "2025-12-08T11:13:55",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/profile/photos/3001345/original/logobig.png",
    "price": "$100-$200",
    "days": 2,
    "orders": 1,
    "industry": "Technology"
  },
  {
    "id": "69280e4da616c2418b281b0d",
    "name": "nickharris10",
    "country": "United States",
    "countryCode": "US",
    "rating": 5,
    "comment": "Fantastic to work with. Thank you so much!!",
    "date": "2025-11-27T09:21:31",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/f333c8802644f6c316da5bd339204f0e-1630272855753/d8ea543b-0230-4124-b51b-d5576e35e173.jpeg",
    "price": "$50-$100",
    "days": 5,
    "orders": 1,
    "industry": "Financial_services_or_banking"
  },
  {
    "id": "691d2ed750695d4c5d31e3e7",
    "name": "rogerlic",
    "country": "Italy",
    "countryCode": "IT",
    "rating": 5,
    "comment": "I highly recommend Masab to anyone looking for advanced AI systems, business automation, conversational interfaces or full-stack development. I approached him with the idea of building a complete business management system powered by multilingual AI. The goal was simple but extremely complex in execution: allow our team to manage CRM, HR, projects, tasks, timesheets and calendar events just by talking to the system in natural language in multiple languages. He delivered it!",
    "date": "2025-11-19T03:06:32",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/e790d36de24015303aec344ef05d3b3f-1679384515936/89e0ec51-8d33-4faa-9635-4363017dbece.png",
    "price": "$400-$600",
    "days": 19,
    "orders": 1,
    "industry": null
  },
  {
    "id": "69160d6c599f193eccc1324a",
    "name": "manelpassos",
    "country": "Portugal",
    "countryCode": "PT",
    "rating": 5,
    "comment": "Great to work with Masab. Masab is very professional and he really want to do a good job. Always asking for feedback. Great choice.",
    "date": "2025-11-13T16:55:08",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/db98401468ba19f383aec79357c1b63d-1764926975916/7e766688-6999-4e40-b66e-0d9d53031daf.jpg",
    "price": "$400-$600",
    "days": 26,
    "orders": 3,
    "industry": null
  },
  {
    "id": "68de9a305277566091be90bd",
    "name": "riansh_kamra",
    "country": "Canada",
    "countryCode": "CA",
    "rating": 5,
    "comment": "He is very hardworking, polite, and professional. He consistently shows dedication to his work and maintains a positive and respectful attitude.",
    "date": "2025-10-02T15:49:48",
    "avatar": null,
    "price": "$50-$100",
    "days": 26,
    "orders": 2,
    "industry": null
  },
  {
    "id": "68bd8d65fe0fc3692004e29b",
    "name": "alessandroirace",
    "country": "Italy",
    "countryCode": "IT",
    "rating": 5,
    "comment": "He responds fast, communicates a lot, and works very hard.",
    "date": "2025-09-07T14:19:56",
    "avatar": null,
    "price": "Up to $50",
    "days": 1,
    "orders": 1,
    "industry": "Technology"
  },
  {
    "id": "68a6e6e6a4f0e21e2e4e47a1",
    "name": "rjr_factive",
    "country": "United States",
    "countryCode": "US",
    "rating": 5,
    "comment": "very great working with Masab! will definitely work with him again",
    "date": "2025-08-21T09:52:08",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/20a1be670847b7badb9876921f999061-1868224131735372000161/JPEG_20241228_014639_29728234955102398.jpg",
    "price": "$100-$200",
    "days": 10,
    "orders": 1,
    "industry": "Technology"
  },
  {
    "id": "687a66c02a1ca343ca7f0a0c",
    "name": "amanjoshi752004",
    "country": "India",
    "countryCode": "IN",
    "rating": 5,
    "comment": "Outstanding Work, Highly Recommended! I had the pleasure of working with P Scribbles on a project that involved both website optimization and Python automation, and I couldn't be happier with the results. They quickly understood my requirements, identified areas to improve performance, and implemented clean, efficient code that made a huge difference in both speed and user experience. What really stood out was their technical expertise, clear communication, and professionalism throughout the process. They not only delivered exactly what I asked for but also suggested improvements I hadn't considered, saving me time and money in the long run. If you're looking for someone reliable, skilled, and easy to work with for web optimization or automation tasks, look no further. I'll definitely be hiring P Scribbles again!",
    "date": "2025-07-18T15:53:33",
    "avatar": null,
    "price": "Up to $50",
    "days": 19,
    "orders": 6,
    "industry": null
  },
  {
    "id": "6857c1bb824b33196a80f820",
    "name": "amanjoshi752004",
    "country": "India",
    "countryCode": "IN",
    "rating": 5,
    "comment": "Working with Masab Farooque was an absolute pleasure. He delivered outstanding results on a complex Python automation project, exceeding all expectations in both speed and quality. His code was clean, efficient, and exceptionally well-documented. Masab demonstrated deep technical expertise, proactive communication, and a strong understanding of the project requirements from day one. He even suggested improvements that added great value to the outcome. I highly recommend Masab to anyone looking for a reliable and skilled Python developer. I'll definitely be working with him again for future automation tasks. 10/10!",
    "date": "2025-06-22T09:11:15",
    "avatar": null,
    "price": "Up to $50",
    "days": 9,
    "orders": 6,
    "industry": null
  },
  {
    "id": "67ffdb4e8d3ebd71d36bc39f",
    "name": "zohaib_0ali",
    "country": "United States",
    "countryCode": "US",
    "rating": 5,
    "comment": "Working with p_scribbles was smooth and super professional again. I needed data scraped from a men's clothing store, and he delivered everything exactly as I asked, will definitely work again with him if the situation arises",
    "date": "2025-04-16T23:27:27",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/3ccd166c58789b8fef318bb3dd1ca4e8-1733156872988/b0ef3fdf-c93c-4a2f-8a92-80d26bfb2bc9.jpg",
    "price": "Up to $50",
    "days": 1,
    "orders": 2,
    "industry": null
  },
  {
    "id": "679508e2310c6021aea611bd",
    "name": "zohaib_0ali",
    "country": "United States",
    "countryCode": "US",
    "rating": 5,
    "comment": "Outstanding SEO work! Masab delivered excellent results, improving my website's ranking and traffic significantly. Communication was clear, and they went above and beyond to meet my needs. Highly recommend and will hire again!",
    "date": "2025-01-26T22:39:37",
    "avatar": "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/3ccd166c58789b8fef318bb3dd1ca4e8-1733156872988/b0ef3fdf-c93c-4a2f-8a92-80d26bfb2bc9.jpg",
    "price": "Up to $50",
    "days": 4,
    "orders": 2,
    "industry": null
  }
];
